#!/bin/sh
curl https://raw.githubusercontent.com/ajayhn/userdata-scripts/master/raw/testbed_all_in_one.py > /opt/contrail/utils/fabfile/testbeds/testbed.py
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

# temporary fixups till committed in repo
sed -i "s/'1.04' in rls/rls and '1.04' in rls/" /opt/contrail/utils/fabfile/tasks/provision.py
sed -i 's/220k/300k/' /opt/contrail/contrail_installer/contrail_setup_utils/setup.py

#cd /opt/contrail/utils && fab setup_all
