#!/bin/sh
sudo echo "deb http://${SERVER}/opencontrail-r120/ opencontrail-r120 main" >> /etc/apt/sources.list
sudo echo "deb http://${SERVER}/opencontrail-thirdparty/ opencontrail-thirdparty main" >> /etc/apt/sources.list
sudo echo "deb http://${SERVER}/opencontrail-stock/ opencontrail-stock main" >> /etc/apt/sources.list
sudo apt-get update
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack-database
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack-config default-jre sysv-rc
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack-control
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack-analytics
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack-webui nodejs=0.8.15-1contrail1
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack-vrouter
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes fabric contrail-fabric-utils

# for avoiding 'sudo: unable to resolve host' in AWS
echo $(hostname -I | cut -d\  -f1) $(hostname) | sudo tee -a /etc/hosts
