#!/bin/sh
curl https://raw.githubusercontent.com/ajayhn/userdata-scripts/master/raw/testbed_all_in_one.py?token=1607150__eyJzY29wZSI6IlJhd0Jsb2I6YWpheWhuL3VzZXJkYXRhLXNjcmlwdHMvbWFzdGVyL3Jhdy90ZXN0YmVkX2FsbF9pbl9vbmUucHkiLCJleHBpcmVzIjoxNDEyOTkwMjEwfQ%3D%3D--85b7b3ef29de4a27d78c66f442dfaeb9ba5ae307 > /opt/contrail/utils/fabfile/testbeds/testbed.py
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
#cd /opt/contrail/utils && fab setup_all
