#!/bin/sh
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes contrail-openstack-control
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes fabric contrail-fabric-utils
