#!/bin/sh
echo "deb http://192.241.237.46/opencontrail-r120/ opencontrail-r120 main" >> /etc/apt/sources.list
echo "deb http://192.241.237.46/opencontrail-thirdparty/ opencontrail-thirdparty main" >> /etc/apt/sources.list
echo "deb http://192.241.237.46/opencontrail-stock/ opencontrail-stock main" >> /etc/apt/sources.list
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes contrail-openstack-database
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes contrail-openstack-config default-jre sysv-rc
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes contrail-openstack-control
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes contrail-openstack-analytics
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes contrail-openstack-webui nodejs=0.8.15-1contrail1
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes contrail-openstack
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes fabric contrail-fabric-utils
